# Generated by Django 3.1.8 on 2022-03-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slackid', models.CharField(blank=True, default='', max_length=100)),
                ('learning_unit', models.IntegerField()),
                ('exercise_notebook', models.IntegerField()),
                ('score', models.FloatField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
